candidates/urls.py
from django.urls import path, include


from candidates.views import *
app_name = 'candidates'
urlpatterns = [
    path('home/', home, name='home'),
    path('details/', candidate_details, name='details'),
    path('job_search_list/', job_search_list, name='job_search_list'),
    
   
    path('profile/', my_profile, name='my-profile'),
    path('delete_skills/', delete_skill, name='skill-delete'),
    path('edit_profile/', edit_profile, name='edit-profile'),
    path('profile/<int:pk>', profile_view, name='profile-view'),
    
    path('job_detcails/<int:pk>/', job_detail, name='job_details'),
    
    path('job/<int:pk>/save/', save_job, name='save-job'),
    path('saved_job_list/', saved_jobs, name='saved-jobs'),

    path('job/<int:pk>/apply/', apply_job, name='apply_job'),
    path('applied_job_list/', applied_jobs, name='applied-jobs'),
    
    path('job/<int:pk>/remove/', remove_job, name='remove-job'),
]
     

jobPortalPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('recruiter/', include('recruiter.urls')),
    path('candidates/', include('candidates.urls')),
    path('', include('pwa.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include


from users.views import *
app_name = 'users'
urlpatterns = [

    path('home/',home, name='home'),
    path('login/',login_view, name='login'),
    path('register/',registration_view, name='register'),
    path('logout/',logout_view, name='logout')
]

candidates/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from autoslug import AutoSlugField
from django_countries.fields import CountryField
from recruiter.models import Job
from django.utils import timezone


from django.contrib.auth import get_user_model

User = get_user_model()

CHOICES = (
    ('Full Time', 'Full Time'),
    ('Part Time', 'Part Time'),
    ('Internship', 'Internship'),
    ('Remote', 'Remote'),
)


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True, related_name='profile')
    full_name = models.CharField(max_length=200, null=True, blank=True)
    country = CountryField(null=True, blank=True)
    location = models.CharField(max_length=255, null=True, blank=True)
    resume = models.FileField(upload_to='resumes', null=True, blank=True)
    grad_year = models.IntegerField(blank=True)
    looking_for = models.CharField(
        max_length=30, choices=CHOICES, default='Full Time', null=True)
    slug = AutoSlugField(populate_from='user', unique=True)

    def get_absolute_url(self):
        return "/profile/{}".format(self.slug)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.name


class Skill(models.Model):
    skill = models.CharField(max_length=200)
    user = models.ForeignKey(
        User, related_name='skills', on_delete=models.CASCADE)


class SavedJobs(models.Model):
    job = models.ForeignKey(
        Job, related_name='saved_job', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='saved', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.job.title


class AppliedJobs(models.Model):
    job = models.ForeignKey(
        Job, related_name='applied_job', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='applied_user', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.job.title

candidates/forms.py
from django import forms
from .models import Profile, Skill

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['full_name', 'country', 'location',
                  'resume', 'grad_year', 'looking_for' ]


class NewSkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['skill']

candidates/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from recruiter.models import Job,Applicants, Selected
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from .models import Profile, Skill, AppliedJobs, SavedJobs
from .forms import NewSkillForm,  ProfileUpdateForm
from django.contrib import messages
from users.decortor import is_candidate,check_ac_type_candidates_or_recruiter
from django.contrib.auth.decorators import user_passes_test

from django.db.models import Q


# Create your views here.
@login_required
def home(request):
    context={
        
    }
    return render(request, 'home.html', context)


def candidate_details(request):
    return render(request, 'candidates/details.html')


@login_required
@user_passes_test(is_candidate)
def job_search_list(request):
    
    query = request.GET.get('jobs')
    
    location = request.GET.get('location')
   

    if query or location:
        # Perform the search query using Q objects
        results = Job.objects.filter(
            Q(title__icontains=query) |
            Q(skills_req__icontains=query) |
            Q(company__icontains=query) |
            Q(job_type__icontains=query),
            location__icontains=location
        ).order_by('-date_posted')
        
    else:
        # If both query and location are empty, show all jobs
        results = Job.objects.all()
        
    paginator = Paginator(results, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'jobs': page_obj,
        'query': query,
    }
    return render(request, 'candidates/job_search_list.html', context)


def my_profile(request):
    
    user = request.user
    
    profile = Profile.objects.filter(user=user).first()
    
    user_skills = Skill.objects.filter(user=user)
    
    if request.method == 'POST':
        form = NewSkillForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = user
            data.save()
            return redirect('candidates:my-profile')
    else:
        form = NewSkillForm()
    context = {
        'user': user,
        'profile': profile,
        'skills': user_skills,
        'form': form,
        'profile_page': "active",
    }
    return render(request, 'candidates/profile.html', context)


@login_required
@user_passes_test(is_candidate)
def delete_skill(request, pk=None):
    if request.method == 'POST':
        id_list = request.POST.getlist('choices')
        for skill_id in id_list:
            Skill.objects.get(id=skill_id).delete()
        return redirect('candidates:my-profile')
    
    
@login_required
@user_passes_test(is_candidate)    
def edit_profile(request):
    username = request.user
    profile = Profile.objects.filter(user=username).first()
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = username
            data.save()
            return redirect('candidates:my-profile')
    else:
        form = ProfileUpdateForm(instance=profile)
    context = {
        'form': form,
    }
    return render(request, 'candidates/edit_profile.html', context )


@login_required
@user_passes_test(is_candidate)
def apply_job(request, pk):
    
    username = request.user

    job = get_object_or_404(Job, id=pk)
  
    applied, created = AppliedJobs.objects.get_or_create(job=job, user=username)
    
    if created:
    
        applicant, creation = Applicants.objects.get_or_create(job=job, applicant=username)
    
        messages.success(request, "Apply Job {} successfully.".format(job.title),
                             extra_tags='alert alert-success alert-dismissible fade show')
    else:
        messages.warning(request, "Already Apply Job {} .".format(job.title),
                             extra_tags='alert alert-success alert-dismissible fade show')
    
    return redirect("candidates:job_search_list")
    # return HttpResponseRedirect('candidates/job/{}'.format(job.id))
    
@login_required
@user_passes_test(is_candidate)
def job_detail(request,pk):
    
    job = get_object_or_404(Job, id=pk) 
    
    profile = Profile.objects.filter(user=request.user).select_related('user').first()
    
    has_applied = AppliedJobs.objects.filter(user=request.user).filter(job=job).exists()
    
    has_saved = SavedJobs.objects.filter(user=request.user).filter(job=job).exists()
      
    context={
        
        'job':job,
        'profile':profile,
        'has_applied':has_applied,
        'has_saved':has_saved
    }

    return render(request, 'candidates/job_details.html', context)

@login_required
@user_passes_test(is_candidate)
def profile_view(request, pk):
    profile = Profile.objects.filter(user_id=pk).first()
    username = profile.user
    user_skills = Skill.objects.filter(user=username)
    context = {
        'username':username,
        'profile': profile,
        'skills': user_skills,
    }
    return render(request, 'candidates/profile.html', context)

@login_required
@user_passes_test(is_candidate)
def save_job(request, pk):
    user = request.user
    job = get_object_or_404(Job, id=pk)
    saved, created = SavedJobs.objects.get_or_create(job=job, user=user)
    print(created)
    print(saved)
    return redirect('candidates:job_search_list')



@login_required
@user_passes_test(is_candidate)
def saved_jobs(request):
    jobs = SavedJobs.objects.filter(
        user=request.user).order_by('-date_posted')
   
    return render(request, 'candidates/saved_jobs.html', {'jobs': jobs, 'candidate_navbar': 1})


@login_required
def applied_jobs(request):
    jobs = AppliedJobs.objects.filter(
        user=request.user).order_by('-date_posted')
    statuses = []
    for job in jobs:
        if Selected.objects.filter(job=job.job).filter(applicant=request.user).exists():
            statuses.append(0)
        elif Applicants.objects.filter(job=job.job).filter(applicant=request.user).exists():
            statuses.append(1)
        else:
            statuses.append(2)
    zipped = zip(jobs, statuses)
    return render(request, 'candidates/applied_jobs.html', {'zipped': zipped, 'candidate_navbar': 1})



@login_required
def remove_job(request, pk):
    user = request.user
    job = get_object_or_404(Job, id=pk)
    saved_job = SavedJobs.objects.filter(job=job, user=user).first()
    saved_job.delete()
    return redirect('candidates:job_search_list')

candidates/templates/candidates/applied_jobs.html
{% extends "base.html" %} {% load static %} {% block content %}
<br /><br />
<div>
  <h3 class="text-center"><b>Applied Jobs</b></h3>
  <hr my-2 />
  <div class="row">
    {% for job, status in zipped %}
    <div class="col-md-6">
      <div class="card card-signin my-2">
        <span class="ml-3 mt-3">
          <a href="{% url 'candidates:job_details' job.job.pk %}"
            ><h4 class="text-dark">
              <b>{{job.job.title}} ({{job.job.job_type}})</b>
            </h4></a
          >
          <p style="font-size: 17px">
            {{job.job.company}}<br />{{job.job.location}}
          </p>
          <p style="font-size: 15px">
            {{job.job.description|truncatewords:30}} -
            <a href="{% url 'candidates:job_details' job.job.pk %}">Read More</a>
          </p>
        </span>
        <div class="card-footer">
          {% if status == 0 %}
          <span style="font-size: 16px"
            >Application Status:
            <b class="text-success text-uppercase ml-2">Selected</b></span
          >
          {% elif status == 1%}
          <span style="font-size: 16px"
            >Application Status:
            <b class="text-primary text-uppercase ml-2">In Process</b></span
          >
          {% else %}
          <span style="font-size: 16px"
            >Application Status:
            <b class="text-danger text-uppercase ml-2">Rejected</b></span
          >
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

candidates/templates/candidates/details.html
{% extends "base.html" %} {% load static %} {% block content %}
<br /><br />
<div style="background-color: white">
  <div class="row">
    <div class="col-md-6">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-4 text-center">Get your next job here!</h1>
        <p class="lead text-center">
          Wondering how to get a great job, we are here to help!
        </p>
        <p class="lead text-center">
          <a
            class="btn btn-primary btn-lg"
            href="{% url 'candidates:home' %}"
            role="button"
            >Search for Jobs Now!</a
          >
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <img
        class="img-fluid"
        src="https://dl.dropboxusercontent.com/s/9t7rpn96uwxhm0e/2895265.jpg?dl=0"
        alt="Hiring Image"
      />
    </div>
  </div>
  <div class="row">
    <div class="col md-6 border-right">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">Always Free!</h1>
        <p class="lead text-center">
          No more doing payments to get the perfect job! We offer free lifetime
          service to job seekers!
        </p>
        <p class="lead text-center">
          Search through the wide variety of jobs and choose one that suits your
          needs, all for free!
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">Get Relevant jobs!</h1>
        <p class="lead text-center">
          Get jobs that suits your needs directly! No need to search through
          various jobs and deal with many filters.
        </p>
        <p class="lead text-center">
          Just complete your profile and get relevant jobs based on your skills!
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 md-8 lg-6 mx-auto">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">More to come soon!</h1>
        <p class="lead text-center">
          Many more features coming soon to enhance your job search experience
          and take it to a whole new level!
          <br />What are you waiting for? Get started today!
        </p>
        <p class="lead text-center">
          <a
            class="btn btn-primary btn-lg"
            href="{% url 'candidates:home' %}"
            role="button"
            >Start the Job Search!</a
          >
        </p>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

candidates/templates/candidates/edit_profile.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %}
{% block content %} <br /><br />
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-md-10 col-lg-8 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h3 class="text-center">
            <b>Update Your Profile</b>
          </h3>
          <form class="form-signin" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
              <br />
              {{ form|crispy }}
            </fieldset>
            <div class="form-group">
              <button class="btn btn-lg btn-primary btn-block" type="submit">
                Update</button
              ><br /><br />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

candidates/templates/candidates/job_details.html
{% extends "base.html" %} {% load static %} {% block content %}
<br /><br />
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h3>
            <b>{{job.title}} ({{job.job_type}})</b>
          </h3>
          <p style="font-size: 18px">{{job.company}}, {{job.location}}</p>

          {% if job.link %}
            <a class="btn btn-warning btn-lg" href="{{job.link}}"><b>Apply On Company's Website</b></a>
          {% else %} 
                
            {% if not has_applied %}
            
                {% if profile.resume %}
                    <a class="btn btn-warning btn-lg" href="{% url 'candidates:apply_job' job.pk %}"><b>Apply Now</b></a>
                {%else %}
                    <a class="btn btn-danger btn-lg" href="{% url 'candidates:edit-profile' %}"><b>Add Resume to apply!</b></a>
                {%endif%}
            {% else %}
                <a class="btn btn-success btn-lg" href="{% url 'candidates:applied-jobs' %}"><b>Applied!</b></a>
            {% endif %} 
          {%endif%} 

          {% if not has_saved %}
            <a class="btn btn-primary btn-lg ml-2" href="{% url 'candidates:save-job' job.pk %}"><b>Save</b></a>
          {% else %}
            <a class="btn btn-danger btn-lg ml-2" href="{% url 'candidates:remove-job' job.pk %}"><b>Remove</b></a>
          {% endif %}
          <hr my-2 />
          <span style="font-size: 18px"><b>Job Description</b></span>
          <p style="white-space: pre-wrap; font-size: 16px">
            {{ job.description }}
          </p>
          <hr my-2 />
          <p><b class="mr-2">Skills Required:</b>{{job.skills_req}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

candidates/templates/candidates/job_search_list.html
{% extends 'base.html'%}

{% load static %}

{% block content%}
    <div>
        <form class="form-signin mt-4" action= "{% url 'candidates:job_search_list'%}" method="get">

            <div class="row">

                <div class="col-md-6">
                    <input name="jobs" type="text" class="form-control" placeholder="Enter Job Title, Skills, Type or Company ">
                    <br />
                </div>

                <div class="col-md-6">
                    <input name="location" type="text" class="form-control" placeholder="Enter Job Location" />
                    <br />
                </div>

                <div class="from-group">

                    <button class="btn btn-lg btn-primary btn-block" type="submit">Search jobs</button>

                </div>

            </div>

        </form>

        <hr my-2 >
        {% if jobs %}
        <div class="row">
            {% for job in jobs %}
            <div class="col-md-6"> 
                <div class="card card-signin my-2">
                    <span class="ml-3 mt-3">
                        <a href=""><h4 class="text-dark"><b>{{job.title}} ({{job.job_type}})</b> </h4>   </a>

                        <p style="font-size: 17px;">{{job.company}}<br />{{job.location}}</p>

                        <p style="font-size: 15px;">{{job.description|truncatewords:30}} - <a href="{% url 'candidates:job_details' job.id%}">Read More</a></p>
                    </span>
                    <div class="card-footer">
                        <span style="font-size: 14px"> Posted On {{job.date_posted|date:"F d, Y"}}

                        </span>


                    </div>


                </div>


            </div>
            {% endfor  %}
            <br />
            <div class="pagination">
                <span class="step-links">
                    {% if jobs.has_previous %}
                        <a class='btn btn-info'href="?page=1{% if request.GET.jobs %}&p={{ request.GET.jobs }}{% endif %}{% if request.GET.location %}&q={{ request.GET.location }}{% endif %}}">Prev</a>
                    {% endif %}
                        <span class="current">
                            Page {{ jobs.number }} of {{ jobs.paginator.num_pages }}.
                        </span>
                    {% if job.has_next %}
                        <a class="btn btn-success" href="?page={{ jobs.next_page_number}} {% if request.GET.jobs %}&jobs={{ request.GET.jobs }}{% endif %}{% if request.GET.location %}&location={{ request.GET.location }}{% endif %}"> Next </a>
                        <a class="btn btn-primary" href="?page={{jobs.paginator.num_pages}} {% if request.GET.jobs %}&p={{ request.GET.jobs }}{% endif %}{% if request.GET.location %}&q={{ request.GET.location }}{% endif %}">Last &raquo </a>
                    {% endif %}
                </span>

            </div>
        {%else%}
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
                    <div class="card card-signin my-5">
                    <div class="card-body">
                        <h5 class="card-title text-center">
                        <b>No relevant jobs found for this search term!</b><br />
                        </h5>
                        <hr my-2 />
                        <h5 class="card-title text-center"><b>Search instead for:</b><br /></h5>
                        <form class="form-signin">
                        <div class="form-group">
                            <a
                            class="btn btn-outline-primary mr-2 mt-2"
                            href="/job/?jobs=software&q="
                            >Software</a
                            >
                            <a
                            class="btn btn-outline-info mr-2 mt-2"
                            href="/job/?jobs=internship&q="
                            >Internship</a
                            >
                            <a
                            class="btn btn-outline-danger mr-2 mt-2"
                            href="/job/?jobs=product+manager&q="
                            >Product Manager</a
                            >
                            <a
                            class="btn btn-outline-secondary mr-2 mt-2"
                            href="/job/?jobs=python&q="
                            >Python</a
                            >
                            <a class="btn btn-outline-dark mr-2 mt-2" href="/job/?jobs=web&location="
                            >Web</a
                            >
                            <a
                            class="btn btn-outline-danger mr-2 mt-2"
                            href="/job/?jobs=android&location="
                            >Android</a
                            >
                            <a
                            class="btn btn-outline-success mr-2 mt-2"
                            href="/job/?jobs=analyst&q="
                            >Analyst</a
                            >
                            <a class="btn btn-outline-info mr-2 mt-2" href="/job/?jobs=sales&location="
                            >Sales</a
                            >
                        </div>
                        </form>
                    </div>
                    </div>
                </div>
                </div>

        </div>

        {% endif %}
    </div>
{% endblock content %}

candidates/templates/candidates/profile.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %}
{% block content %} <br /><br />
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h3 class="text-center">Profile Data</h3>
          <br />
          <form class="form-signin">
            <div class="form-group">
              <p>Name: {{ profile.user.name }}</p>
              <p>Full Name: {{ profile.full_name }}</p>
              <p>Email: {{ profile.user.email }}</p>
              <p>Country: {{ profile.country.name }}</p>
              <p>Location: {{ profile.location }}</p>
              <p>Graduation Year: {{ profile.grad_year }}</p>
              <p>Looking For: {{ profile.looking_for }}</p>
              {% if profile.resume %}
              <p>
                Resume:
                <a href="{{ profile.resume.url }}">Click to View/Download</a>
              </p>
              {% else %}
              <p>Resume: Not Provided</p>
              {% endif %} {% if request.user == u %}
              <hr class="my-4" />
              <a
                class="btn btn-warning btn-block"
                href="{% url 'candidates:edit_profile'%}"
                >Edit Profile</a
              ><br />

              <a class="btn btn-primary btn-block" href=""
                >Saved Jobs</a
              ><br />
              <a
                class="btn btn-success btn-block"
                href=""
                >Applied Jobs</a
              >
              {% endif %}
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h3 class="text-center">Skills ({{ skills.count }})</h3>
          <br />
          {% if request.user != user %}
          <ol>
            {% for skill in skills %}
            <li>{{skill.skill}}</li>
            {% endfor %}
          </ol>
          {% else %}
          <form class="form-signin" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
              <br />
              {{ form|crispy }}
            </fieldset>
            <div class="form-group">
              <button
                class="btn btn-lg btn-outline-primary btn-block"
                type="submit"
              >
                Add Skill</button
              ><br />
            </div>
          </form>
          <br />
          {% if skills %}
          <form
            class="form-signin"
            action="{% url 'candidates:skill-delete' %}"
            method="POST"
          >
            {% csrf_token %} {% for skill in skills %}
            <div>
              <input
                class="mr-2"
                type="checkbox"
                value="{{ skill.id }}"
                name="choices"
              />{{ skill.skill }}
            </div>
            {% endfor %}
            <br />
            <div class="form-group">
              <button
                class="btn btn-lg btn-outline-danger btn-block"
                type="submit"
                name="delete"
              >
                Delete Selected Skills</button
              ><br />
            </div>
          </form>
          {% endif %} {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

candidates/templates/candidates/saved_jobs.html
{% extends "base.html" %} {% load static %} {% block content %}
<br /><br />
<div>
  <h3 class="text-center"><b>Saved Jobs</b></h3>
  <hr my-2 />
  <div class="row">
    {% for job in jobs %}
    <div class="col-md-6">
      <div class="card card-signin my-2">
        <span class="ml-3 mt-3">
          <a href="{% url 'candidates:job_details' job.job.pk %}"
            ><h4 class="text-dark">
              <b>{{job.job.title}} ({{job.job.job_type}})</b>
            </h4></a
          >
          <p style="font-size: 17px">
            {{job.job.company}}<br />{{job.job.location}}
          </p>
          <p style="font-size: 15px">
            {{job.job.description|truncatewords:30}} -
            <a href="{% url 'candidates:job_details' job.job.pk %}">Read More</a>
          </p>
        </span>
        <div class="card-footer">
          <span style="font-size: 14px"
            >Posted on {{job.job.date_posted|date:"F d, Y"}}</span
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}