candidates/urls.py
from django.urls import path, include


from candidates.views import *
app_name = 'candidates'
urlpatterns = [
    path('home/', home, name='home'),
    path('details/', candidate_details, name='details'),
    path('job_search_list/', job_search_list, name='job_search_list'),
    
   
    path('profile/', my_profile, name='my-profile'),
    path('delete_skills/', delete_skill, name='skill-delete'),
    path('edit_profile/', edit_profile, name='edit-profile'),
    path('profile/<int:pk>', profile_view, name='profile-view'),
    
    path('job_detcails/<int:pk>/', job_detail, name='job_details'),
    
    path('job/<int:pk>/save/', save_job, name='save-job'),
    path('saved_job_list/', saved_jobs, name='saved-jobs'),

    path('job/<int:pk>/apply/', apply_job, name='apply_job'),
    path('applied_job_list/', applied_jobs, name='applied-jobs'),
    
    path('job/<int:pk>/remove/', remove_job, name='remove-job'),
]
     

jobPortalPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('recruiter/', include('recruiter.urls')),
    path('candidates/', include('candidates.urls')),
    path('', include('pwa.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

recruiter/urls.py
from django.urls import path, include


from recruiter.views import *
app_name = 'recruiter'
urlpatterns = [

    path('rec_detail', get_rec_details, name='rec-detail'),
    path('listJobs/',getJob_list, name='listJobs'),
    path('add_jobs/',add_job, name='add_jobs'),
    path('job/<slug>', job_detail, name='add-job-detail'),
    
    path('job/selected_list/', selected_list, name='selected_list'),
    path('job/applicants_list/', applicants_list, name='applicants_list'),
    
    path('job/<int:job_id>/select_applicant/<int:can_id>/', select_applicant, name='select_applicant'),
    
    path('job/<int:job_id>/reject_applicant/<int:can_id>/', reject_applicant, name='reject_applicant'),
    
    path('search_candidate/', search_candidate, name='search_candidate')

]

users/urls.py
from django.urls import path, include


from users.views import *
app_name = 'users'
urlpatterns = [

    path('home/',home, name='home'),
    path('login/',login_view, name='login'),
    path('register/',registration_view, name='register'),
    path('logout/',logout_view, name='logout')
]

recruiter/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.utils import timezone
from autoslug import AutoSlugField
from django_countries.fields import CountryField
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()

CHOICES = (
    ('Full Time', 'Full Time'),
    ('Part Time', 'Part Time'),
    ('Internship', 'Internship'),
    ('Remote', 'Remote'),
)


class Job(models.Model):
    recruiter = models.ForeignKey(
        User, related_name='jobs', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    company = models.CharField(max_length=200)
    location = models.CharField(max_length=255)
    description = models.TextField()
    skills_req = models.CharField(max_length=200)
    job_type = models.CharField(
        max_length=30, choices=CHOICES, default='Full Time', null=True)
    link = models.URLField(null=True, blank=True)
    slug = AutoSlugField(populate_from='title', unique=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title
    
    
class Applicants(models.Model):
    job = models.ForeignKey(
        Job, related_name='applicants', on_delete=models.CASCADE)
    applicant = models.ForeignKey(
        User, related_name='applied', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.applicant)


class Selected(models.Model):
    job = models.ForeignKey(Job, related_name='select_job', on_delete=models.CASCADE)
    applicant = models.ForeignKey(User, related_name='select_applicant', on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.applicant)

recruiter/forms.py
from django import forms
from .models import Job


class NewJobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'company', 'location',
                  'description', 'skills_req', 'job_type', 'link']
        help_texts = {
            'skills_req': 'Enter all the skills required each separated by commas.',
            'link': 'If you want candidates to apply on your company website rather than on our website, please provide the link where candidates can apply. Otherwise, please leave it blank or candidates would not be able to apply directly!',
        }


class JobUpdateForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'company', 'location',
                  'description', 'skills_req', 'job_type', 'link']
        help_texts = {
            'skills_req': 'Enter all the skills required each separated by commas.',
            'link': 'If you want candidates to apply on your company website rather than on our website, please provide the link where candidates can apply. Otherwise, please leave it blank or candidates would not be able to apply directly!',
        }

recruiter/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.core.paginator import Paginator
from .models import Job, Selected, Applicants
from django.contrib.auth.decorators import login_required
from .forms import NewJobForm
from django.contrib import messages
from candidates.models import Profile
from users.decortor import *
from django.contrib.auth.decorators import user_passes_test
from django.db.models import Q
# Create your views here.

def getJob_list(request):
    
    jobs = Job.objects.filter(recruiter=request.user).order_by('-date_posted')
    paginator = Paginator(jobs, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'manage_jobs_page': "active",
        'jobs': page_obj,
        'rec_navbar': 1,
    }
    return render(request, 'recruiter/listJobs.html', context)


@user_passes_test(is_recruiter)
def add_job(request):
    
    user = request.user
    
    if request.method == "POST":
        form = NewJobForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.recruiter = user
            data.save()
            return redirect('recruiter:listJobs')
    else:
        form = NewJobForm()
    context = {
        'add_job_page': "active",
        'form': form,
        'rec_navbar': 1,
    }
    return render(request, 'recruiter/add_job.html', context)


def job_detail(request, slug):
    job = get_object_or_404(Job, slug=slug)
  
    context = {
        'job': job,
        'rec_navbar': 1,
    }
    
    return render(request, 'recruiter/job_detail.html', context)


def get_rec_details(request):
 
   
    context = {
        'rec_home_page': "active",
        'rec_navbar': 1,
    }
    return render(request, 'recruiter/rec_details.html', context)


@login_required
@user_passes_test(is_recruiter)
def edit_job(request, slug):
    user = request.user
    job = get_object_or_404(Job, slug=slug)
    if request.method == "POST":
        form = NewJobForm(request.POST, instance=job)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect('add-job-detail', slug)
    else:
        form = NewJobForm(instance=job)
    context = {
        'form': form,
        'rec_navbar': 1,
        'job': job,
    }
    return render(request, 'recruiters/edit_job.html', context)

@login_required
@user_passes_test(is_recruiter)
def selected_list(request):
    objects = Selected.objects.select_related('job', 'applicant')
    
    profiles = []
    for obj in objects:
        job = obj.job       
        selected_applicants = objects.filter(job=job).order_by('date_posted')
        for applicant in selected_applicants:
            profile = Profile.objects.filter(user=applicant.id).first()
            if profile is not None:
                profiles.append(profile)
    
    context = {
        'rec_navbar': 1,
        'profiles': profiles,
        'job': job,
    }
    
    return render(request, 'recruiter/selected_list.html', context)

@login_required
@user_passes_test(is_recruiter)
def applicants_list(request):
    
    objects = Applicants.objects.select_related('job', 'applicant')
    profiles = []
    for obj in objects:
        job = obj.job       
        applicants = objects.filter(job=job).order_by('date_posted')
        for applicant in applicants:
            profile = Profile.objects.filter(user=applicant.id).first()
            if profile is not None:
                profiles.append(profile)

    context = {
        'rec_navbar': 1,
        'job':job,
        'applicants':applicants,
        'profiles':profiles
        # 'applicants':applicants
        
    }
    print(context)
    
    return render(request, 'recruiter/applicants_list.html', context)

@login_required
@user_passes_test(is_recruiter)
def select_applicant(request, can_id, job_id):
    job = get_object_or_404(Job, id=job_id)
    profile = get_object_or_404(Profile, user_id=can_id)
    user = profile.user
    
    selected, created = Selected.objects.get_or_create(job=job, applicant=user)
    if created:
        applicant = Applicants.objects.filter(job=job, applicant=user).first()
        if applicant is None:
            messages.error(request, "Applicant {} not select successfully.".format(user.name),
                             extra_tags='alert alert-warning alert-dismissible fade show')
            return redirect('recruiter:applicants_list')
        applicant.delete()
        messages.success(request, "Applicant {} select successfully.".format(user.name),extra_tags='alert alert-success alert-dismissible fade show')
    else:
        messages.warning(request, "Applicant {} already selected.".format(user.name),extra_tags='alert alert-success alert-dismissible fade show')
    
    return redirect('recruiter:applicants_list')


@login_required
@user_passes_test(is_recruiter)
def reject_applicant(request, can_id, job_id):
    job = get_object_or_404(Job, id=job_id)
    profile = get_object_or_404(Profile, user_id=can_id)
    user = profile.user
    
    applicant = Applicants.objects.filter(job=job, applicant=user).first()
    
    if applicant is None:
        messages.error(request, "Applicant {} not reject successfully.".format(user.name),
                            extra_tags='alert alert-warning alert-dismissible fade show')
        return redirect('recruiter:applicants_list')
    applicant.delete()
    messages.success(request, "Applicant {} rejected successfully.".format(user.name),extra_tags='alert alert-success alert-dismissible fade show')

    return redirect('recruiter:applicants_list')

def search_candidate(request):
    
    looking_for = request.GET.get('looking_for') #full time part time
    
    location = request.GET.get('location') 
    
    
    if location or looking_for:
        # Perform the search query using Q objects
        results = Profile.objects.filter(
            Q(looking_for__icontains=looking_for) |
            Q(full_name__icontains=looking_for) |
            Q(grad_year__icontains=looking_for),
            location__icontains=location
        )
        
    else:
        # If both query and location are empty, show all jobs
        results = Profile.objects.all()
        
    paginator = Paginator(results, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'search_candidates_page': "active",
        'rec_navbar': 1,
        'profiles': page_obj,
    }

    return render(request, 'recruiter/search_candidate.html', context)

recruiter/templates/recruiter/add_job.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %}
{% block content %} <br />
<div class="container">
  {%if request.user.account_type == 'recruiter'%}
  <div class="row">
    <div class="col-sm-10 col-md-10 col-lg-8 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h3 class="text-center">
            <b>Add New Job Post</b>
          </h3>
          <span style="font-size: 14px">
            <p class="text-center">
              (Please read the helper texts provided with the fields carefully.
              <br />Mistakes can make your job perform poorly!)
            </p>
        </span>
          <form class="form-signin" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
              <br />
              {{ form|crispy }}
            </fieldset>
            <div class="form-group">
              <button class="btn btn-lg btn-success btn-block" type="submit">
                Post Job</button
              ><br /><br />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {%else%}
    <p> You are not recruiter</p>
    <p> Please Login as recruiter</p>
  {% endif %}  
</div>
{% endblock content %}

recruiter/templates/recruiter/applicants_list.html
{% extends "base.html" %} {% load static %} {% block content %}
<br /><br />
<div>
  <h3 class="text-center">
    <b>Applicants for {{job.title}}</b>
  </h3>
  <br />
  {% if profiles %}
  <div class="row">
    {% for profile in profiles %}
    <div class="col-md-4">
      <div class="card card-signin my-5">
        <span class="ml-3 mt-3">
          <a href="{% url 'candidates:profile-view' profile.pk %}">
            {% if profile.full_name %}
            <h4 class="text-dark">
              <b>{{profile.full_name}}</b>
            </h4>
            {% else %}
            <h4 class="text-dark">
              <b>{{profile.user.name}}</b>
            </h4>
            {% endif %}
          </a>
          <p style="font-size: 17px">
            {{profile.user.email}}<br />{{profile.country.name}}
          </p>
          {% if profile.resume %}
          <a href="{{profile.resume.url}}">Click here to view the resume</a>
          {% else %}
          <p>No Resume Provided!</p>
          {% endif %}
        </span>

        <div class="card-footer">
          <a
            class="btn btn-success mr-2"
            href="{% url 'recruiter:select_applicant' can_id=profile.user_id job_id=job.id %}"
            >Select
          </a>
          <a
            class="btn btn-danger mr-2"
            href="{% url 'recruiter:reject_applicant' can_id=profile.user_id job_id=job.id %}"
            >Reject
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p class="text-center">
    No new applications for now! Please check back later! Go to
    <a href="{% url 'recruiter:selected_list' job.id %}">selected list</a> by clicking
    here!
  </p>

  <br />
  {% endif %}
</div>
{% endblock content %}

recruiter/templates/recruiter/job_detail.html
{%extends 'base.html'%}
{%block content%}

<div style="background-color: white">
    <div class="row">
      <div class="col-md-6">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-4 text-center">
            Hire the next best candidate here!
          </h1>
          <p class="lead text-center">
            Hiring can be a tedious task. Let us make it easy for you!
          </p>
          <p class="lead text-center">
            <a
              class="btn btn-primary btn-lg"
              href=""
              role="button"
              >Hire Now!</a
            >
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <img
          class="img-fluid"
          src="https://dl.dropboxusercontent.com/s/t80cdspg3wjoquj/4565.jpg?dl=0"
          alt="Hiring Image 2"
        />
      </div>
    </div>
    <div class="row">
      <div class="col md-6 border-right">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">
            Easy to hire! Get started in a few simple steps!
          </h1>
          <p class="lead text-center">
            We make hiring as simple as possible. No more hassles. Just sign in,
            add necessary details about the job post and you are ready to go!
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">Unlimited job posts. For Free!</h1>
          <p class="lead text-center">
            Post any number of job posts you want for free. We do not charge you
            for just posting jobs!
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col md-6 border-right">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">
            Want to get results faster? Go Premium!
          </h1>
          <p class="lead text-center">
            Job Posts of premium users enjoy more visibility and thus get more
            applicants in a shorter period of time!<br /><br />All of this for a
            small fee only!
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">
            Get recommended candidates for your job!
          </h1>
          <p class="lead text-center">
            Get candidates recommendation for each job post and make your hiring
            much faster by directly contacting them.<br /><br /><i
              >Available in free plan for a limited time!</i
            >
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-10 md-8 lg-6 mx-auto">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">
            Search through the candidate database!
          </h1>
          <p class="lead text-center">
            Search and see resumes of every candidate on our database. Get the
            best candidate suitable for your jobs and directly contact them
            resulting in fast hires!<br /><br /><i
              >Avaialable in free plan for a limited time!</i
            >
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-10 md-8 lg-6 mx-auto">
        <div style="background: transparent !important" class="jumbotron">
          <h1 class="display-5 text-center">More features coming soon!</h1>
          <p class="lead text-center">
            We believe in making the hiring process easier. Thus, we will keep
            adding new features as we progress and will continue to help you in
            hiring the best talents!<br /><br />So, what are you waiting for? Get
            the early access benefits and enjoy premium services for free for a
            limited time!
          </p>
          <p class="lead text-center">
            <a
              class="btn btn-primary btn-lg"
              href=""
              role="button"
              >Post jobs now!</a
            >
          </p>
        </div>
      </div>
    </div>
    {% endblock %}
  </div>
{%endblock content %}

recruiter/templates/recruiter/listJobs.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

<div class="container">
  {%for job in jobs %}
    {% if request.user == job.recruiter %}
      <div class="row">
        <div class="col-md-12">
          <div class="card card-signin my-5">
            <div class="card-body">
              <h3>
                <b>{{job.title}} ({{job.job_type}})</b>
              </h3>
              <p style="font-size: 18px">{{job.company}}, {{job.location}}</p>
              {% if not job.link %}
              <a
                class="btn btn-info btn-lg mr-2"
                href="{% url 'recruiter:applicants_list' %}"
                ><b>Applicants List</b></a>
                <a
                class="btn btn-info btn-lg mr-2"
                href="{% url 'recruiter:selected_list' %}"
                ><b>Selected List</b></a>

              {% endif %}
              <a
                class="btn btn-warning btn-lg mr-2"
                href=""
                ><b>Edit Job Post</b></a
              >
              <a
                class="btn btn-danger btn-lg"
                href=""
                ><b>Search Relevant Candidates</b></a
              >
              <hr my-2 />
              <span style="font-size: 18px"><b>Job Description</b></span>
              <p style="white-space: pre-wrap; font-size: 16px">
                {{ job.description }}
              </p>
              <hr my-2 />
              <p><b class="mr-2">Skills Required:</b>{{job.skills_req}}</p>
            </div>
          </div>
        </div>
      </div>
    {% else %}
      <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-8 mx-auto">
          <div class="card card-signin my-5">
            <div class="card-body">
              <h3 class="text-center">You do not have access to this page!</h3>
            </div>
          </div>
        </div>
      </div>
    {%endif%}
  {% endfor %}
</div>
{% endblock content %}

recruiter/templates/recruiter/rec_details.html
{% extends "base.html" %} {% load static %} 
{% block content %}
<br /><br />
<div style="background-color: white">
  <div class="row">
    <div class="col-md-6">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-4 text-center">
          Hire the next best candidate here!
        </h1>
        <p class="lead text-center">
          Hiring can be a tedious task. Let us make it easy for you!
        </p>
        <p class="lead text-center">
          <a
            class="btn btn-primary btn-lg"
            href="{% url 'recruiter:add_jobs' %}"
            role="button"
            >Hire Now!</a
          >
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <img
        class="img-fluid"
        src="https://dl.dropboxusercontent.com/s/t80cdspg3wjoquj/4565.jpg?dl=0"
        alt="Hiring Image 2"
      />
    </div>
  </div>
  <div class="row">
    <div class="col md-6 border-right">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">
          Easy to hire! Get started in a few simple steps!
        </h1>
        <p class="lead text-center">
          We make hiring as simple as possible. No more hassles. Just sign in,
          add necessary details about the job post and you are ready to go!
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">Unlimited job posts. For Free!</h1>
        <p class="lead text-center">
          Post any number of job posts you want for free. We do not charge you
          for just posting jobs!
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col md-6 border-right">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">
          Want to get results faster? Go Premium!
        </h1>
        <p class="lead text-center">
          Job Posts of premium users enjoy more visibility and thus get more
          applicants in a shorter period of time!<br /><br />All of this for a
          small fee only!
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">
          Get recommended candidates for your job!
        </h1>
        <p class="lead text-center">
          Get candidates recommendation for each job post and make your hiring
          much faster by directly contacting them.<br /><br /><i
            >Available in free plan for a limited time!</i
          >
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 md-8 lg-6 mx-auto">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">
          Search through the candidate database!
        </h1>
        <p class="lead text-center">
          Search and see resumes of every candidate on our database. Get the
          best candidate suitable for your jobs and directly contact them
          resulting in fast hires!<br /><br /><i
            >Avaialable in free plan for a limited time!</i
          >
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 md-8 lg-6 mx-auto">
      <div style="background: transparent !important" class="jumbotron">
        <h1 class="display-5 text-center">More features coming soon!</h1>
        <p class="lead text-center">
          We believe in making the hiring process easier. Thus, we will keep
          adding new features as we progress and will continue to help you in
          hiring the best talents!<br /><br />So, what are you waiting for? Get
          the early access benefits and enjoy premium services for free for a
          limited time!
        </p>
        <p class="lead text-center">
          <a
            class="btn btn-primary btn-lg"
            href="{% url 'recruiter:add_jobs' %}"
            role="button"
            >Post jobs now!</a
          >
        </p>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

recruiter/templates/recruiter/search_candidate.html
{%extends 'base.html' %}
{% load static %}
{% block content %}
<br />
<div class="contener">
  <h3 class="text-center">
    <b>Search Candidates</b>
  </h3>
  <form class="form-signin mt-4" action="{% url 'recruiter:search_candidate' %}"  method="get">

    <div class="row">

        <div class="col-md-6">
            <input name="looking_for"  type="text" class="form-control" placeholder="For Job Type (Full Time, Intern etc.), full_name, grad_year"/> <br />
        </div>


        <div class="col-md-6">
            <input name="location"  type="text" class="form-control" placeholder="Enter Location of Choice"/> <br />
        </div>
    
    </div>
    <div class="form-group">
        <button class="btn btn-lg btn-primary btn-block" type="submit">
        Apply Filters
        </button>
    </div>
  </form>
  {% if profiles%}
  <div class="row">
      {% for profile in profiles %}
        <div class="col-md-4">
            <div class="card card-signin my-2">
                <span class="ml-3 mt-3">
                <a href="{% url 'candidates:profile-view' profile.pk %}">
                    {% if profile.full_name %}
                    <h4 class="text-dark">
                    <b>{{profile.full_name}}</b>
                    </h4>
                    {% else %}
                    <h4 class="text-dark">
                    <b>{{profile.user.name}}</b>
                    </h4>
                    {% endif %}
                </a>
                <p style="font-size: 17px">
                    {{profile.user.email}}<br />{% if profile.location %}
                    {{profile.location}} {% else %} {{profile.country.name}} {% endif %}
                </p>
                </span>
                <div class="card-footer">
                    {% if profile.resume %}
                    <a href="{{ profile.resume.url }}">Click to view resume</a>
                    {% else %}
                    <p>No resume available.</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
   </div>
   <br />

   <div class="pagination">
    <span class="step-links">
      {% if profiles.has_previous %}
      <a
        class="btn btn-info"
        href="?page=1{% if request.GET.looking_for %}&p={{ request.GET.looking_for }}{% endif %}{% if request.GET.location %}&q={{ request.GET.location }}{% endif %}"
        >&laquo; First</a
      >
      <a
        class="btn btn-danger"
        href="?page={{ profiles.previous_page_number }}{% if request.GET.looking_for %}&p={{ request.GET.looking_for }}{% endif %}{% if request.GET.location %}&q={{ request.GET.location }}{% endif %}"
        >Prev</a
      >
      {% endif %}
      <span class="current">
        Page {{ profiles.number }} of {{ profiles.paginator.num_pages }}.
      </span>
      {% if profiles.has_next %}
      <a
        class="btn btn-success"
        href="?page={{ profiles.next_page_number }}{% if request.GET.looking_for %}&p={{ request.GET.looking_for }}{% endif %}{% if request.GET.location %}&q={{ request.GET.location }}{% endif %}"
        >Next</a
      >
      <a
        class="btn btn-primary"
        href="?page={{ profiles.paginator.num_pages }}{% if request.GET.looking_for %}&p={{ request.GET.looking_for }}{% endif %}{% if request.GET.location %}&q={{ request.GET.location }}{% endif %}"
        >Last &raquo;</a
      >
      {% endif %}
    </span>
  </div>

  {% else %}
  <p class="text-center">No candidates found!</p>
  <br />
  {% endif %}

</div>
{% endblock content%}

recruiter/templates/recruiter/selected_list.html
{% extends "base.html" %} {% load static %} {% block content %}
<br /><br />
<div>
  <h3 class="text-center">
    <b>Selected Applicants for  {{job.title}}</b>
  </h3>
  <br />
  {% if profiles %}
  <div class="row">
    {% for profile in profiles %}
    <div class="col-md-4">
      <div class="card card-signin my-5">
        <span class="ml-3 mt-3">
          <a href="{% url 'candidates:profile-view' profile.pk %}">
            {% if profile.full_name %}
            <h4 class="text-dark">
              <b>{{profile.full_name}}</b>
            </h4>
            {% else %}
            <h4 class="text-dark">
              <b>{{profile.user.name}}</b>
            </h4>
            {% endif %}
          </a>
          <p style="font-size: 17px">
            {{profile.user.email}}<br />{{profile.country.name}}
          </p>
          {% if profile.resume %}
          <a href="{{profile.resume.url}}">Click here to view the resume</a>
          {% else %}
          <p>No Resume Provided!</p>
          {% endif %}
        </span>

        <div class="card-footer">
            <a
              class="btn btn-success mr-2"
              href="{% url 'candidates:profile-view' profile.pk %}"
              >Visit Profile
            </a>
          </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p class="text-center">
    No applicant has been selected till now! Select some
    <a href="{% url 'applicants_list'%}">applicant</a> first!
  </p>
  <br />
  {% endif %}
</div>
{% endblock content %}