jobPortalPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('recruiter/', include('recruiter.urls')),
    path('candidates/', include('candidates.urls')),
    path('', include('pwa.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include


from users.views import *
app_name = 'users'
urlpatterns = [

    path('home/',home, name='home'),
    path('login/',login_view, name='login'),
    path('register/',registration_view, name='register'),
    path('logout/',logout_view, name='logout')
]

users/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):

  def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
    if not email:
        raise ValueError('Users must have an email address')
    now = timezone.now()
    email = self.normalize_email(email)
    user = self.model(
        email=email,
        is_staff=is_staff, 
        is_active=True,
        is_superuser=is_superuser, 
        last_login=now,
        date_joined=now, 
        **extra_fields
    )
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_user(self, email, password, **extra_fields):
    return self._create_user(email, password, False, False, **extra_fields)

  def create_superuser(self, email, password, **extra_fields):
    user=self._create_user(email, password, True, True, **extra_fields)
    return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    ACCOUNT_TYPE_CHOICES = (
        ('admin', 'Admin'),
        ('candidates', 'candidates'),
        ('recruiter', 'recruiter')
    )
    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPE_CHOICES)
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
    
    
    def __str__(self):
        return self.email

users/forms.py
from django import forms
from .models import CustomUser
# from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import get_user_model

User = get_user_model()

class RegistrationForm(UserCreationForm):
    """
      Form for Registering new users 
    """
    email = forms.EmailField(max_length=60, help_text = None)
    class Meta:
        model = CustomUser
        fields = ('email', 'name', 'password1', 'password2', 'account_type')
      

    def __init__(self, *args, **kwargs):
        """
          specifying styles to fields 
        """
        super(RegistrationForm, self).__init__(*args, **kwargs)
      
        for fieldname in ['email','name', 'password1', 'password2', 'account_type']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs.update({'class': 'form-control '})

class UserAuthenticationForm(forms.ModelForm):
    """
      Form for Logging in  users
    """
    password  = forms.CharField(label= 'Password', widget=forms.PasswordInput)

    class Meta:
        model  =  CustomUser
        fields =  ('email', 'password')
        widgets = {
                   'email':forms.TextInput(attrs={'class':'form-control'}),
                   'password':forms.TextInput(attrs={'class':'form-control'})
        }
    def __init__(self, *args, **kwargs):
        """
          specifying styles to fields 
        """
        super(UserAuthenticationForm, self).__init__(*args, **kwargs)
        for field in (self.fields['email'],self.fields['password']):
            field.widget.attrs.update({'class': 'form-control '})

    def clean(self):
        if self.is_valid():

            email = self.cleaned_data.get('email')
            password = self.cleaned_data.get('password')
            if not authenticate(email=email, password=password):
                raise forms.ValidationError('Invalid Login')
              
              

users/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from django.contrib.auth import (
                                  authenticate,
                                  logout ,
                                  login
                              )
from .forms import (
                    
                    UserAuthenticationForm,
                    RegistrationForm
                    
                )

# Create your views here.

def home(request):
    context = {
        
    }
    return render(request, 'home.html', context)


    
def  login_view(request):
    """
      Renders Login Form
    """
    context = {}
    user = request.user
   
    if user.is_authenticated:
        return redirect('users:home')
        # return redirect('users:home')
    if request.POST:
        form    = UserAuthenticationForm(request.POST)
        email   = request.POST.get('email')
        password = request.POST.get('password')
        
        user =  authenticate(email=email, password=password)
        
        if user:
            login(request, user)
            if user.account_type == 'admin':
                return redirect('users:home')
            elif user.account_type == 'candidates':
                return redirect('users:home')
            elif user.account_type == 'recruiter':
                return redirect('users:home')
            messages.success(request, "Logged In",extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('users:home')
            # return redirect('users:home')
        else:
            pass
            # messages.error(,"please Correct Below Errors",)
    else:
        form = UserAuthenticationForm()
    context['login_form'] = form
    
    return render(request, "users/login.html", context)
    
    
def logout_view(request):
    
    logout(request)
    messages.success(request, "Logged Out",  extra_tags='alert alert-success alert-dismissible fade show')
    return redirect('users:home')


def registration_view(request):
    """
      Renders Registration Form 
    """
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST, use_required_attribute=False)
        if form.is_valid():
            form.save()
            email    = form.cleaned_data.get('email')
            messages.success(request, "You have been Registered as {}".format(email), extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('users:login')
        else:
            messages.error(request, "Please Correct Below Errors")
            context['registration_form'] = form
    else:
        form = RegistrationForm(use_required_attribute=False)
        context['registration_form'] = form
    return render(request, "users/register.html", context)

users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}

<section class="vh-100" style="background-color: #508bfc;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">

                        <h3 class="mb-5">Sign in</h3>
            
                        <form id="login_form" class="form" method="post" action="{% url 'users:login' %}">
                        {% csrf_token %} <!-- for security reasons -->
                        {% if form.errors %}
                        <p>username or password not correct</p>
                        {% endif %}

                        {{login_form.as_p}} <!-- rendering form as paragraph -->
                        
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
                    
                        {% comment %} <input type="submit" class="btn  btn-outline-info" value="Login"> {% endcomment %}

                        </form>
                        <p ><a class="px-2 mx-2 btn btn-link text-decoration-none" href="{%url 'users:register' %}">Not a Member?</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
    <!-- Section: Design Block -->
<section class="text-center">
    <!-- Background image -->
    <div class="p-5 bg-image" style="
          background-image: url('https://mdbootstrap.com/img/new/textures/full/171.jpg');
          height: 300px;
          "></div>
    <!-- Background image -->
  
    <div class="card mx-4 mx-md-5 shadow-5-strong" style="
          margin-top: -100px;
          background: hsla(0, 0%, 100%, 0.8);
          backdrop-filter: blur(30px);
          ">
      <div class="card-body py-5 px-md-5">
  
        <div class="row d-flex justify-content-center">
          <div class="col-lg-8">
            {% if messages %}
            <div class="mgs-area">
                <div class="mgs-item">
                {% for message in messages %}
                <span {% if message.tags %} class="nav_item message-{{ message.tags }} " {% endif %}> {{ message }} </span>
                {% endfor %}
                </div>
            </div>
                {% endif %}
            {% comment %} <h2 class="fw-bold mb-5">Sign up now</h2> {% endcomment %}
                    {% comment %} <div class="container jumbotron"> {% endcomment %}
                        {% if registered %}
                            <strong>Thank You for Registering with Us.</strong>
                            <a href="{% url 'index' %}" class="btn-link btn">Return to the HomePage</a><br>
                        {% else %}
                        <h2 class="col-md-6 mb-4">Sign up now</h2>
                            {% comment %} <strong class="display-3 mb-4">Register Here... </strong> {% endcomment %}
                            <form action="{% url 'users:register' %}" class="pt-3" method="POST">
                                {% csrf_token %}
                                {{ registration_form.as_p }}
                                {% comment %} <input type="submit" name="submit" value="Register" class="btn btn-success"> {% endcomment %}
                                <button type="submit" class="btn btn-primary btn-block mb-4">
                                    Sign up
                                    </button>
                                <p class="p-2 m-1">Already a Member? <a href="{% url 'users:login' %}">Sign In Here...</a></p>
                            </form>

                        {% endif %}
                </div>     
            </div> 
        </div>     
    </div>         
</div>                                                              
{% endblock %} 












{% comment %} {% extends 'main.html' %}

{%block title %}Register{% endblock  %}

{% block content %}

    <div class="container jumbotron">
        {% if registered %}
            <strong>Thank You for Registering with Us.</strong>
            <a href="{% url 'index' %}" class="btn-link btn">Return to the HomePage</a><br>
        {% else %}
            <strong class="display-3 mb-4">Register Here... </strong>
            <form action="{% url 'users:register' %}" class="pt-3" method="POST">
                {% csrf_token %}
                {{ registration_form.as_p }}
                <input type="submit" name="submit" value="Register" class="btn btn-success">
                <p class="p-2 m-1">Already a Member? <a href="{% url 'users:login' %}">Sign In Here...</a></p>
            </form>
        {% endif %}
    </div>
{% endblock %} {% endcomment %}