candidates/urls.py
from django.urls import path, include


from candidates.views import *
app_name = 'candidates'
urlpatterns = [
    path('home/', home, name='home'),
    path('details/', candidate_details, name='details'),
    path('job_search_list/', job_search_list, name='job_search_list'),
    
   
    path('profile/', my_profile, name='my-profile'),
    path('delete_skills/', delete_skill, name='skill-delete'),
    path('edit_profile/', edit_profile, name='edit-profile'),
    path('profile/<int:pk>', profile_view, name='profile-view'),
    
    path('job_detcails/<int:pk>/', job_detail, name='job_details'),
    
    path('job/<int:pk>/save/', save_job, name='save-job'),
    path('saved_job_list/', saved_jobs, name='saved-jobs'),

    path('job/<int:pk>/apply/', apply_job, name='apply_job'),
    path('applied_job_list/', applied_jobs, name='applied-jobs'),
    
    path('job/<int:pk>/remove/', remove_job, name='remove-job'),
]
     

jobPortalPrj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('recruiter/', include('recruiter.urls')),
    path('candidates/', include('candidates.urls')),
    path('', include('pwa.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

recruiter/urls.py
from django.urls import path, include


from recruiter.views import *
app_name = 'recruiter'
urlpatterns = [

    path('rec_detail', get_rec_details, name='rec-detail'),
    path('listJobs/',getJob_list, name='listJobs'),
    path('add_jobs/',add_job, name='add_jobs'),
    path('job/<slug>', job_detail, name='add-job-detail'),
    
    path('job/selected_list/', selected_list, name='selected_list'),
    path('job/applicants_list/', applicants_list, name='applicants_list'),
    
    path('job/<int:job_id>/select_applicant/<int:can_id>/', select_applicant, name='select_applicant'),
    
    path('job/<int:job_id>/reject_applicant/<int:can_id>/', reject_applicant, name='reject_applicant'),
    
    path('search_candidate/', search_candidate, name='search_candidate')

]

users/urls.py
from django.urls import path, include


from users.views import *
app_name = 'users'
urlpatterns = [

    path('home/',home, name='home'),
    path('login/',login_view, name='login'),
    path('register/',registration_view, name='register'),
    path('logout/',logout_view, name='logout')
]

templates/base.html
{% load static %} {% load pwa %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    {% progressive_web_app_meta %}
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
  
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Lato"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="https://dl.dropboxusercontent.com/s/ecyb1drs5j1jyjf/styles.css?dl=0"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://dl.dropboxusercontent.com/s/xmxsoypfvfvsisb/footer.css?dl=0"
    />

    <style>
      body {
        font-family: "Lato";
        font-size: 20px;
      }
    </style>

    {% block cssfiles %}{% endblock cssfiles %}
    <title>Job AaDa</title>
  </head>

  <body>
   
    {% if not rec_navbar %}
    {% if request.user.account_type == 'candidates'%}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <a class="navbar-brand" href="{% url 'candidates:details' %}">
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link {{ home_page }}" href="{% url 'candidates:home' %}"
            >Job Search</a
          >
          <a
            class="nav-item nav-link {{ profile_page }}"
            href="{% url 'candidates:my-profile' %}"
            >My Profile</a
          >
          <a
            class="nav-item nav-link {{ intel_page }}"
            href=""
            >Get Relevant Jobs</a
          >
          <a class="nav-item nav-link {{ account_page }}" href="">My Account</a>

          <a class="nav-item nav-link {{ search_page }}" href="{% url 'candidates:job_search_list' %}">Search</a>

          {% if user.is_authenticated %}
          <a
            class="nav-item nav-link btn btn-danger ml-4 mr-4 text-light"
            href="{% url 'users:logout' %}"
            >Logout</a
          >
          <a class="nav-item nav-link" href="{% url 'recruiter:add_jobs' %}"
            >Recruiters/ Employers</a
          >
          {% else %}
          <a
            class="nav-item nav-link btn btn-success ml-4 mr-4 text-light"
            href="{% url 'users:login' %}"
            >Login</a
          >
          <a class="nav-item nav-link" href="{% url 'recruiter:rec-detail' %}"
            >Recruiters/ Employers</a
          >
          {% endif %}
        </div>
      </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <a class="navbar-brand" href="{% url 'candidates:details' %}">
      <b>Job Aada</b>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a
            class="nav-item nav-link {{ rec_home_page }}"
            href="{% url 'recruiter:rec-detail' %}"
            >Home</a
          >
          <a
            class="nav-item nav-link {{ add_job_page }}"
            href="{% url 'recruiter:add_jobs' %}"
            >Add Job Post</a
          >
          <a
            class="nav-item nav-link {{ manage_jobs_page }}"
            href=""
            >Manage Your Job Posts</a
          >
          <a
            class="nav-item nav-link {{ search_candidates_page }}"
            href=""
            >Search Candidates</a
          >
          {% if user.is_authenticated %}
          <a
            class="nav-item nav-link btn btn-danger ml-4 mr-4 text-light"
            href="{% url 'users:logout' %}"
            >Logout</a
          >
          {% else %}

          <a
            class="nav-item nav-link btn btn-success ml-4 mr-4 text-light"
            href="{% url 'users:login' %}"
            >Login</a
          >
          {% endif %}

          <a class="nav-item nav-link" href="{% url 'candidates:home' %}"
            >Job Seekers/Candidates</a
          >
        </div>
      </div>
    </nav>

    {% endif %}
    {%endif%}
    {% include 'message.html' %}
    <div class="container">{% block content %}{% endblock content %}</div>

    <footer>
      <hr my-2 />
      <div class="row">
        <div class="col-sm-6 col-md-4 footer-navigation">
          <h3>Job Aada</h3>
          <p class="links">
            <a href="{% url 'candidates:details' %}">Job Seekers</a
            ><strong> · </strong
            ><a href="{% url 'recruiter:rec-detail' %}">Recruiters</a
            ><strong> · </strong><a href="">Pricing</a>
            <strong> · </strong
            ><a href="">Terms of Service</a>
            <strong> · </strong
            ><a href="">Privacy Policy</a>
          </p>
          <p class="company-name">
            Job Aada @ 2023<br /><small class="text-muted"
              >All rights reserved!</small
            ><br />
          </p>
        </div>
        <div class="col-sm-6 col-md-4 footer-contacts">
          <div>
            <span class="fa fa-map-marker footer-contacts-icon"></span>
            <p><span class="new-line-span">Job Aada</span>Pune, India</p>
          </div>

          <div>
            <i class="fa fa-envelope footer-contacts-icon"></i>
            <p><a href="#" target="_blank">jobAada@gmail.com</a></p>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-md-4 footer-about">
          <h4>About the company</h4>
          <p>
            Job Aada  mission is to make hiring easier. We aim to save
            time for both job seekers and recruiters and to make the hiring
            process smoother. We continue to innovate and find new solutions to
            make hiring process simpler.
          </p>
          <div class="social-links social-icons">
            <a href="#"><i class="fa fa-facebook"></i></a
            ><a href="#"><i class="fa fa-twitter"></i></a
            ><a href="https://www.linkedin.com/company/job Aada/"
              ><i class="fa fa-linkedin"></i
            ></a>
          </div>
        </div>
      </div>
      <p class="text-center" style="font-size: 12px">
        <a href="https://www.freepik.com/vectors/"
          >Image vectors by - www.freepik.com</a
        >
      </p>
    </footer>

    <!-- JS Files -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block jsfiles %}{% endblock jsfiles %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-10 col-lg-8 mx-auto">
        <h2><b>Search Jobs !!!!!!!!!!</b></h2>
        <form
          class="form-signin mt-4"
          action=""
          method="get"
        >
          <input
            name="p"
            type="text"
            class="form-control"
            placeholder="Enter Job Title, Skills, Type or Company"
          /><br />
          <input
            name="q"
            type="text"
            class="form-control"
            placeholder="Enter Job Location"
          />
          <br />
          <div class="form-group">
            <button class="btn btn-lg btn-primary btn-block" type="submit">
              Search Jobs
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="container mt-3">
      <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-8 mx-auto">
          {% if user.is_authenticcated %}
          <p class="text-center">
            <b
              >Recruiters/Employers -
              <a href="recruiters:add_jobs">Post a Job</a></b
            >
          </p>
          {% else %}
          <p class="text-center">
            <b
              >Recruiters/Employers -
              <a href="recruiters:add_jobs">Post a Job</a></b
            >
          </p>
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 mx-auto">
          <div class="card card-signin my-5">
            <div class="card-body">
              <h5 class="card-title text-center">
                <b>Some Popular Search terms:</b><br />
              </h5>
              <hr my-2 />
  
              <form class="form-signin">
                <div class="form-group">
                  <a
                    class="btn btn-outline-primary mr-2 mt-2"
                    href=""
                    >Software</a
                  >
                  <a
                    class="btn btn-outline-info mr-2 mt-2"
                    href=""
                    >Internship</a
                  >
                  <a
                    class="btn btn-outline-danger mr-2 mt-2"
                    href=""
                    >Product Manager</a
                  >
                  <a
                    class="btn btn-outline-secondary mr-2 mt-2"
                    href=""
                    >Python</a
                  >
                  <a class="btn btn-outline-dark mr-2 mt-2" href=""
                    >Web</a
                  >
                  <a
                    class="btn btn-outline-danger mr-2 mt-2"
                    href=""
                    >Android</a
                  >
                  <a
                    class="btn btn-outline-success mr-2 mt-2"
                    href=""
                    >Analyst</a
                  >
                  <a
                    class="btn btn-outline-info mr-2 mt-2"
                    href=""
                    >Sales</a
                  >
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

templates/message.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}